distribution_code_name: "fcitx-rime"
distribution_name: Rime
distribution_version: 0.2.3
install_time: "Tue Jan 10 13:07:10 2017"
installation_id: "7a9b9acb-a5dc-4650-b245-6bbd4e80ecb5"
rime_version: 1.2.9
update_time: "Thu Sep  7 11:05:31 2017"